
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FirstREST.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Utilizador
{

    public Utilizador()
    {

        this.Carts = new HashSet<Cart>();

    }


    public int Id { get; set; }

    public string Username { get; set; }

    public string Pass { get; set; }

    public string Email { get; set; }

    public string Fullname { get; set; }

    public string CodCliente { get; set; }

    public string Address { get; set; }



    public virtual ICollection<Cart> Carts { get; set; }

}

}
